2023-10-10 18:47:36,935 INFO Program is start
2023-10-10 18:47:39,147 ERROR File not found
Traceback (most recent call last):
  File "D:\python_3_course_labs\3lab\main.py", line 18, in main
    open(file_name, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'dd'
